export const PETITION_TEMPLATES = [
    {
        id: "tarifas-bancarias",
        title: "Tarifas Bancárias",
        description: "Ação declaratória de inexistência de débito c/c repetição de indébito e danos morais para cobranças indevidas em conta corrente.",
        tags: ["Bancário", "Consumidor"],
        content_summary: "Modelo completo para revisão de tarifas.",
        damage_label: "Valor Total dos Descontos",
        active: true,
    },
    {
        id: "seguro-contrato-veiculos",
        title: "Seguro Contrato de Veículos",
        description: "Ação de inexigibilidade de seguro c/c danos materiais e morais por venda casada de seguro em contrato de financiamento de veículo.",
        tags: ["Bancário", "Consumidor"],
        content_summary: "Modelo para cancelamento de seguro embutido em financiamento de veículo.",
        damage_label: "Valor Total do Seguro Cobrado",
        active: true,
    },
    {
        id: "rmc",
        title: "Cartão de Crédito RMC",
        description: "Anulação de Reserva de Margem Consignável (RMC) indevida em benefício previdenciário com pedido de indenização.",
        tags: ["Consumidor", "Idoso"],
        content_summary: "Petição inicial para casos de RMC não solicitado.",
        damage_label: "Soma dos Descontos RMC",
        active: false,
    },
    {
        id: "atraso-voo",
        title: "Atraso/Cancelamento de Voo",
        description: "Ação indenizatória por danos morais e materiais decorrentes de atraso superior a 4 horas ou cancelamento de voo.",
        tags: ["Cível", "Aéreo"],
        content_summary: "Indenização por danos morais e materiais em voos.",
        damage_label: "Prejuízo Material (Gastos)",
        active: false,
    },
    {
        id: "plano-saude-cirurgia",
        title: "Negativa de Cirurgia/Home Care",
        description: "Obrigação de fazer com pedido de tutela de urgência para liberar cirurgia, medicamento ou home care negado pelo plano.",
        tags: ["Saúde", "Liminar"],
        content_summary: "Tutela de urgência para saúde.",
        damage_label: "Valor do Orçamento (Se houver)",
        active: false,
    },
    {
        id: "divorcio-consensual",
        title: "Divórcio Consensual",
        description: "Petição inicial para divórcio amigável, com ou sem partilha de bens e guarda de menores, pronta para homologação.",
        tags: ["Família", "Civil"],
        content_summary: "Minuta de acordo de divórcio.",
        damage_label: "Valor Total dos Bens",
        active: false,
    },
    {
        id: "usucapiao-extrajudicial",
        title: "Usucapião Extrajudicial",
        description: "Requerimento para reconhecimento de property via cartório, conforme Provimento 65/CNJ.",
        tags: ["Imobiliário", "Cartório"],
        content_summary: "Requerimento para cartório.",
        damage_label: "Valor Venal do Imóvel",
        active: false,
    },
    {
        id: "golpe-pix",
        title: "Golpe do Pix",
        description: "Ação de restituição de valores contra o banco por falha na segurança (Súmula 479 STJ) e mecanismos anti-fraude.",
        tags: ["Bancário", "Fraude"],
        content_summary: "Ação de restituição para golpes digitais.",
        damage_label: "Valor do Pix Fraudulento",
        active: false,
    },
    {
        id: "liminar-concurso",
        title: "Mandado de Segurança (Concurso)",
        description: "Peça para anulação de questões ou garantia de nomeação de candidato aprovado dentro das vagas.",
        tags: ["Administrativo", "Concurso"],
        content_summary: "MS para concursos públicos.",
        damage_label: "Valor da Causa (Estimado)",
        active: false,
    },
    {
        id: "multa-transito",
        title: "Defesa de Autuação/Suspensão CNH",
        description: "Recurso administrativo ou judicial para anulação de multas e processos de suspensão do direito de dirigir.",
        tags: ["Trânsito", "Administrativo"],
        content_summary: "Defesa prévia e recurso JARI.",
        damage_label: "Valor da Multa (R$)",
        active: false,
    },
];

export const ACTIVE_PETITION_TEMPLATES = PETITION_TEMPLATES.filter(t => t.active);
